### ISSUE TITLE
Documentação da Sprint 4

### ISSUE THREAD

**Issue by rogerioo** [fga-eps-mds/2020.2-Lend.it#105]
## Descrição da Issue
Deve criar o documento de planejamento e outro de conclusão da sprint 4

## Tasks:
- [x] texto com o foco da sprint
- [x] datas de inicio e fim da sprint
- [x] lincar as issues mapeadas
- [x] Colocar métricas
- [x] Colocar resumo do Scrum Master

## Critérios de Aceitação:
- [x] estar na wiki
