### ISSUE TITLE
Documentação Sprint 06

### ISSUE THREAD

**Issue by rogerioo** [fga-eps-mds/2020.2-Lend.it#115]
## Descrição da Issue
Deve criar o documento de planejamento e outro de conclusão da sprint 6

## Tasks:
- [x] texto com o foco da sprint
- [x] datas de inicio e fim da sprint
- [x] linkar as issues mapeadas
- [x] Colocar métricas
- [x] Colocar resumo do Scrum Master

## Critérios de Aceitação:
- [x] estar na wiki
