### ISSUE TITLE
[FIX] Testes nos serviços Python

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#124]
## Descrição da Issue
Testar os serviços do Lendit

## Tasks:
- [x] Testar serviço avaliação
- [ ] Testar serviço usuários
- [x] Testar serviço pedidos

## Critérios de Aceitação:
- [ ] Ter coverage dos testes

**Comment by viniciussaturnino** [comment]
Conteúdo para teste na rota User com jwt: https://www.youtube.com/watch?v=2G_mWfG0DZE&t=1400s
