### ISSUE TITLE
[FIX] Integração gateway

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#125]
## Descrição da Issue
Conectar os serviços do back com o gateway 

## Tasks:
- [x] Integrar com todos os endpoints do User
- [x] Integrar com todos os endpoints do Request

## Critérios de Aceitação:
- [x] Os serviços se comunicando com o front pelo gateway

**Comment by youssef-md** [comment]
Finalizamos a integração com o User e Request, as rotas são:
- `POST /users/user`
- `POST /users/session`
- `GET /requests/product-category`
- `POST /requests/product-category`
- `GET /requests/request`
- `POST /requests/request`
- `PUT /requests/request/:id`
- `DELETE /requests/request:id`
