### ISSUE TITLE
Organizar os assets do sonar

### ISSUE THREAD

**Issue by youssef-md** [fga-eps-mds/2020.2-Lend.it#151]
## Descrição da Issue
Separar os assets do Sonar de cada microserviço em um diretório separado por releases

## Tasks:
- [x] No repositório de documentação, criar uma pasta/diretório com o seguinte nome: analytics-raw-data. Esta pasta deverá conter os TODOS arquivos, antigos e futuros, gerados com as métricas fornecidas pelo sonar, para cada release.
- [x] O nome do arquivo arquivo .json a ser gerado deve seguir o seguinte formato: <fga-eps-mds-2020_2-NOME_PROJETO-DATA_RELEASE>  onde, release_date deve ter o seguinte formato: DD/MM/YYYY

## Critérios de Aceitação:
- [x] Os assets do sonar devem estar organizados seguindo a organização sugerida pelo professor.
