### ISSUE TITLE
Coletar métricas da analise dos dados - Avaliação

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#160]
## Descrição da Issue
Coletar as metricas código do serviço de Avaliação de acordo com os dados gerado pela análise do notebook

## Tasks:
- [ ] Rodar o notebook no repositorio
- [ ] Pegar as métricas
- [ ] Documentar para futura evolução

## Critérios de Aceitação:
- [ ] Estarr de acordo com as instruções do professor
- [ ] Ter métricas coletadas

**Comment by rogerioo** [comment]
Issue descontinuada em virtude das definições do professor.
