### ISSUE TITLE
Criação de CD Front

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#165]
## Descrição da Issue
Criar o CD no serviço de Frontend

## Tasks:
- [ ] Preparar build do front
- [ ] Fazer CD Front

## Critérios de Aceitação:
- [ ] Estar rodando a pipeline de CD
