### ISSUE TITLE
Documento de planejamento da sprint 0

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#20]
## Descrição da Issue
Deve criar o documento de planejamento da sprint 0 

## Tasks:
- [x] texto com o foco da sprint
- [x] datas de inicio e fim da sprint
- [x] lincar as issues mapeadas

## Critérios de Aceitação:
- [x] estar na wiki
