### ISSUE TITLE
Pesquisa de mercado para o produto

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#24]
## Descrição da Issue
Chegamos a um produto inicial, porém, devemos escolher qual nicho nossa aplicação será encaixada.

## Tasks:
- [ ]
- [ ]
- [ ]

## Critérios de Aceitação:
- [x] Links de referência de aplicações concorrentes
- [x] Exemplos diversos de nichos (construção, objetos cotidianos, etc...)
- [x] Pitch das ideias

**Comment by lucasdutraf** [comment]
### Ferramentas e relacionados 
#### Pontos positivos
* Não existe mercado de empréstimo/aluguel de ferramentas, somente de maquinário grande.
* Pode existir um mercado de pessoas interessadas, visto que não há concorrência
* Para pessoas donas de casa, não se contratam serviços por atividades pequenas. Ex: Colocar um quadro, reparar um parafuso solto.
#### Pontos negativos
* Geralmente (pode ser validado via pesquisa) quem se arrisca a utilizar ferramentas para consertos cotidianos já tem uma certa expertise e, provavelmente, já possui seu kit
* A pessoa pode contratar um serviço que o prestador já possua o que ela precisa

### Livros
#### Pontos positivos
* Envolve mais de um ODS
* O mercado existe porém não trás inovações
#### Pontos negativos
* É necessário uma grande maturidade e educação entre os envolvidos
* Já existe aplicações que fazem este papel. Ex: [bookshare](http://www.bookshare.com.br/Home/About)

### Artigos de cozinha de uso "extraordinário"
Ex: Panela de Barro, panelas de pressão, fogão industrial
#### Pontos positivos
* Não existe concorrência
* Pode agregar do ponto de vista ambiental, visto que o tempo de degradação do aço e do alumínio (material comum de fabricação de panelas), por exemplo, é de mais de 100 anos
#### Pontos negativos
* Pode ter baixa adesão por questões sanitárias
* Público alvo restrito?

**Comment by EsioFreitas** [comment]
@lucasdutraf adicionar na wiki
