### ISSUE TITLE
Pesquisa tema ambiental para o produto

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#25]
## Descrição da Issue
Foi levantado a discussão que o foco da aplicação poderia ter dois pontos de partida, o ponto de partida levando em conta necessidades e nuâncias do mercado #24 e o ponto de partida que leva em consideração a colaboração com a redução do impacto ambiental que alguns objetos pode oferecer através do reuso. O que se espera dessa issue são ideias e opções de nichos específicos para direcionarmos nossa aplicação e o porquê dessa escolha. 

## Tasks:
- [x] Task 1
- [x] Task 2
- [x] Task 3

## Critérios de Aceitação:
- [x] Links de referência de aplicações exemplos (se existirem)
- [x] Exemplos diversos de nichos (plásticos, objetos que tem tempo de degradação alto no geral, etc...)
- [x] Pitch das ideias

**Comment by thiagompc** [comment]
Sobre plástico:
https://epocanegocios.globo.com/Brasil/noticia/2019/03/brasil-e-o-4-pais-que-mais-produz-lixo-no-mundo-diz-wwf.html
https://www.ecycle.com.br/6251-impacto-ambiental-do-lixo-plastico.html
"Um estudo realizado durante seis anos pelo 5 Gyres Institute estimou que há cerca de 5,25 trilhões de partículas de plástico flutuando no oceano, o que é equivalente a 269 mil toneladas de plástico."
"O mais alarmante é que, uma vez no ambiente, os microplásticos absorvem substâncias químicas perigosas e são ingeridos por organismos marinhos, penetrando em toda a cadeia alimentar, inclusive a terrestre. Além de absorverem substâncias químicas perigosas persistentes e bioacumulativas, em muitos casos o próprio microplástico é feito de materiais perigosos para os organismos, como no caso de plásticos que contém bisfenóis."
Sobre consumo:
http://www.cienciaecultura.ufba.br/agenciadenoticias/noticias/“poder-de-consumo-e-grande-causador-do-impacto-ambiental”/
"Asher destaca que é fundamental ter um consumo consciente, que implicaria na redução de resíduos gerados. Para o pesquisador, a reciclagem, por exemplo, tem uma eficácia muito baixa; a reutilização é menos nobre. “O que temos que fazer é não ter que reciclar. O produto deve passar pelos seus diversos usos dentro de seu ciclo de vida e ter o máximo de aproveitamento do material”, defende."
"Para tornar a sociedade mais sustentável é preciso mudar velhos hábitos. Ter noção do quanto se gasta, do quanto se desperdiça e fazer um consumo consciente dos produtos. “O sonho de uma sociedade sustentável só será possível a partir do momento em que a sociedade repensar seus modos de consumo, principalmente nas nações mais ricas”, conclui o professor."
http://www.conteudojuridico.com.br/consulta/Artigos/55121/compartilhamento-de-tudo-com-a-economia-colaborativa-para-elevao-do-consumidor-brasileiro
"Para alcançar o desenvolvimento sustentável e uma qualidade de vida mais elevada para todos, os Estados devem reduzir e eliminar os padrões insustentáveis de produção e consumo, e promover políticas demográficas adequadas."

Feito em conjunto com @Thais-ra

**Comment by rogerioo** [comment]
Adicionar ao Doc de Visão #17

**Comment by EsioFreitas** [comment]
@thiagompc ja esta no doc de visão?

**Comment by EsioFreitas** [comment]
@lucasdutraf adicionar junto com a #24 na wiki
