### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#27]
## Descrição da Issue
criação do fluxo do aplicativo para elicitação de requisitos. Segue [CONTEÚDO DE ESTUDO](https://medium.com/aela/wireframe-o-que-%C3%A9-e-como-criar-seu-primeiro-fab2fdecbb56)
ex.: 
* https://pax-app.github.io/Wiki/#/docs/DS/dinamica-e-seminario-2/PrototipoBaixaFidelidade

## Tasks:
- [x] Desenhar no papel como você visualiza a aplicação e seu fluxo.

## Critérios de Aceitação:
- [x] Comentar a entrega nessa issue
- [x] Ser no papel
- [x] Adicionar na wiki

**Comment by thiagompc** [comment]
[prototipo_thiago.pdf](https://github.com/fga-eps-mds/EPS-2020-2-G1/files/5975025/prototipo_thiago.pdf)

**Comment by Thais-ra** [comment]
![photo_2021-02-13_01-20-26](https://user-images.githubusercontent.com/35047444/107841454-c952c200-6d99-11eb-8d10-a94e576a44e8.jpg)
![photo_2021-02-13_01-20-00](https://user-images.githubusercontent.com/35047444/107841459-cf48a300-6d99-11eb-98ff-f70004d2b291.jpg)
![photo_2021-02-13_01-21-43](https://user-images.githubusercontent.com/35047444/107841466-dc659200-6d99-11eb-84de-0d863b408ff7.jpg)
![photo_2021-02-13_01-22-02](https://user-images.githubusercontent.com/35047444/107841469-e5eefa00-6d99-11eb-82c9-f887c0c7bc21.jpg)

**Comment by mateusmaiamaia** [comment]
![Wireframe](https://user-images.githubusercontent.com/48732066/107851774-29be1f80-6deb-11eb-8122-5e5ecfab2a04.jpg)

**Comment by viniciussaturnino** [comment]
![prototipo_vinicius_saturnino](https://user-images.githubusercontent.com/49040839/107852727-2332a680-6df1-11eb-9569-371e064465a2.jpg)

**Comment by Matheusafonsouza** [comment]
![PDF Scanner 13-02-2021 12 22 09 PM (1)-1](https://user-images.githubusercontent.com/42722634/107853756-8a068e80-6df6-11eb-87e0-66eb3302c293.jpg)
![PDF Scanner 13-02-2021 12 21 33 PM-1](https://user-images.githubusercontent.com/42722634/107853760-8a9f2500-6df6-11eb-818b-6723bd81dd5a.jpg)

**Comment by youssef-md** [comment]
![asd](https://user-images.githubusercontent.com/29265857/107857055-cb089e00-6e0a-11eb-981c-ba5a0200681c.jpg)

**Comment by matheusyanmonteiro** [comment]
![WhatsApp Image 2021-02-13 at 15 07 28](https://user-images.githubusercontent.com/49919267/107857671-91399680-6e0e-11eb-8a06-6889d44486ee.jpeg)
![WhatsApp Image 2021-02-13 at 15 07 29](https://user-images.githubusercontent.com/49919267/107857684-a4e4fd00-6e0e-11eb-94fe-eab32da51ec5.jpeg)
![s](https://user-images.githubusercontent.com/49919267/107857712-d52c9b80-6e0e-11eb-8072-9a2478399793.jpeg)

**Comment by lucasdutraf** [comment]
Protótipo de Baixa fidelidade do @EsioFreitas 

![photo_2021-02-13_16-02-05](https://user-images.githubusercontent.com/31940073/107858801-d95bb780-6e14-11eb-8064-ad2129b0271b.jpg)

**Comment by EsioFreitas** [comment]
@youssef-md  precisa colocar na wiki
