### ISSUE TITLE
Protótipo de Média Fidelidade

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#29]
## Descrição da Issue
Criação do protótipo no Figma respeitando o fluxo definido pelo time.

## Tasks:
- [x] Criar componentes
- [x] Criar Telas
- [x] Criar Navegação

## Critérios de Aceitação:
- [x] Ser no Figma
- [x] Respeitar fluxo definido pelo time
- [x] Ter documento na wiki

**Comment by viniciussaturnino** [comment]
Estamos fazendo pareamento todos os dias a noite para desenvolvimento do protótipo no figma.

Link: https://www.figma.com/file/9QMXf9YyVXYTG6hYnwZAHK/Prot%C3%B3tipo-M%C3%A9dia-Fidelidade?node-id=0%3A1

**Comment by matheusyanmonteiro** [comment]
Estamos fazendo o pareamento como o @viniciussaturnino  já citou e aprendendo com o @youssef-md  muitas funcionalidades do figma
Além de entender melhor o fluxo.

**Comment by matheusyanmonteiro** [comment]
Criamos hoje mais algumas telas do protótipo de media fidelidade, como mostra a imagem abaixo.
![figma](https://user-images.githubusercontent.com/49919267/108576543-c6f1ea00-72fc-11eb-8209-e55a8f93f6fa.PNG)
@viniciussaturnino  e eu tivemos algumas ideias de layout mais informações com detalhes melhores  acessar o Link:
https://www.figma.com/file/9QMXf9YyVXYTG6hYnwZAHK/Prot%C3%B3tipo-M%C3%A9dia-Fidelidade?node-id=0%3A1

**Comment by youssef-md** [comment]
Finalizamos a v2 do nosso protótipo!

![Screenshot from 2021-02-20 14-30-26](https://user-images.githubusercontent.com/29265857/108603697-3bbe3600-7388-11eb-833e-d8251cab4a0c.png)

**Comment by EsioFreitas** [comment]
@viniciussaturnino , como esta a documentação dessa issue na wiki?

**Comment by viniciussaturnino** [comment]
Iniciei a documentação no domingo e subi pra branch! O @youssef-md vai adicionar o que falta no doc que é a parte do figma para subir pra wiki
