### ISSUE TITLE
Dojo Flutter

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#30]
## Descrição da Issue
Dar Dojo de Flutter para o time de MDS

## Tasks:
- [x] Criar Dojo pt1
- [x] Dar o Dojo pt1
- [x] Tirar dúvidas dos MDSs pt1
- [x] Criar Dojo pt2
- [x] Dar o Dojo pt2
- [x] Tirar dúvidas dos MDSs pt2

**Comment by youssef-md** [comment]
O primeiro dojô foi dado, nele passei os conceitos base para a criação de um aplicativo em Flutter, como funciona a SDK e um pouco dos Widgets que o Flutter nos fornece.
![sasd](https://user-images.githubusercontent.com/29265857/108448243-19b99c00-7240-11eb-822f-e262288318db.jpg)

**Comment by youssef-md** [comment]
Dojô parte 2 foi dado e gravado para quem quiser reprise: [Vídeo](https://youtu.be/vsWvMFD5ERU) e [GitHub](https://github.com/youssef-md/dojo-flutter)

**Comment by lucasdutraf** [comment]
> Dojô parte 2 foi dado e gravado para quem quiser reprise: [Vídeo](https://youtu.be/vsWvMFD5ERU) e [GitHub](https://github.com/youssef-md/dojo-flutter)

Muito bom @youssef-md !! Parabéns!

**Comment by EsioFreitas** [comment]
Melhor time <3
