### ISSUE TITLE
Questionario

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#38]
## Descrição da Issue
Criação de um questionário para validar publico alvo 

## Tasks:
- [x] Pesquisar sobre o publico algo
- [x] Elaborar perguntas para publico alvo

## Critérios de Aceitação:
- [x] criar documento na wiki

**Comment by lucasdutraf** [comment]
Questionário começou a rodar na quinta-feira (18/02) e ficará aberto até domingo (21/02). No momento constam 169 respostas.
