### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#40]
## Descrição da Issue
Criação de rich picture para enriquecer documentação do fluxo da aplicação. [CONTEUDO](http://www.mspguide.org/tool/rich-picture#:~:text=A%20rich%20picture%20is%20a,to%20illustrate%20graphically%20the%20situation.). 
Ex.: 
* https://pax-app.github.io/Wiki/#/docs/DS/dinamica-e-seminario-1/RichPicture
* https://requisitos-habitica.netlify.app/RichPictures

## Tasks:
- [x] Criação da rich picture

## Critérios de Aceitação:
- [x] Ter pelo menos 1 evolução.
- [x] Ter documento na wiki

**Comment by Matheusafonsouza** [comment]
Rich picture de usuário cedente:
![Untitled - Frame 1 (3)](https://user-images.githubusercontent.com/42722634/108430973-fdf2cd80-7220-11eb-952d-a0729a95ecb2.jpg)

**Comment by Matheusafonsouza** [comment]
Rich picture do usuário que quer algo emprestado: 
![Untitled - Frame 2](https://user-images.githubusercontent.com/42722634/108431709-ff70c580-7221-11eb-9372-9bf0207a2e30.jpg)

**Comment by mateusmaiamaia** [comment]
Rich picture "Posso emprestar algo".
![Rich picture](https://user-images.githubusercontent.com/48732066/108577158-cbb79d80-72fe-11eb-941e-d7066b316566.jpg)

**Comment by mateusmaiamaia** [comment]
Rich picture "Quero algo emprestado"
![Rich picture(1)](https://user-images.githubusercontent.com/48732066/108577195-ee49b680-72fe-11eb-8200-b6b56a48c874.jpg)

**Comment by Matheusafonsouza** [comment]
Rich pictures atualizados
![Untitled - Frame 2](https://user-images.githubusercontent.com/42722634/108605101-d4f14a80-7390-11eb-81d4-ea7f33d1681a.jpg)
![Untitled - Frame 1](https://user-images.githubusercontent.com/42722634/108605103-d6227780-7390-11eb-8d93-42a4ab6c4064.jpg)

**Comment by mateusmaiamaia** [comment]
Rich picture "Posso emprestar algo", atualizado
![Rich picture](https://user-images.githubusercontent.com/48732066/108605109-e0447600-7390-11eb-96bf-d8b0cbf54c88.jpg)

**Comment by EsioFreitas** [comment]
@mateuscunhamaia , como ta a documentacao dessa issue na wiki? 
ps.: não esqueça de colocar as vc versões.
