### ISSUE TITLE
Documentar Prática Ágil

### ISSUE THREAD

**Issue by rogerioo** [fga-eps-mds/2020.2-Lend.it#41]
## Descrição da Issue
Com as definições de rituais feitas, é importante juntar tudo em um único documento e subir na Wiki para que possa ficar bem documentado

## Tasks:
- [x] Condensar definições previamentes definidas em um documento (#8 #9 #10 #11 #12 #13 #14 #15)
- [x] Acrescentar definições que forem relevantes

## Critérios de Aceitação:
- [x] Subir documento na Wiki

## Assignees
@rogerioo
