### ISSUE TITLE
Documento de arquitetura

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#52]
## Descrição da Issue
Iniciar documentação de arquitetura do projeto.

referencias 
* https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/docArquitetura
* https://pax-app.github.io/Wiki/#/docs/DS/dinamica-e-seminario-4-b/DAS

## Tasks:
- [x] Introdução
- [x] Representação Arquitetural
- [x] Requisitos e Restrições Arquiteturais
- [x] Diagrama de Pacotes
- [x] Diagrama de Casos de Uso

## Critérios de Aceitação:
- [x] Usar padrões da comunidade
- [x] Documentar na wiki

**Comment by Thais-ra** [comment]
Criei uma branch pra issue e commitei a estrutura inicial do documento.

**Comment by matheusyanmonteiro** [comment]
Comecei a fazer o diagrama geral de caso de uso.
Criamos um grupo para uma melhor comunicação da atividade.

**Comment by matheusyanmonteiro** [comment]
Diagrama de Caso de uso 40%, peço que verifiquem e me passem feedback se está bom ou ruim e o que precisa ser mudado, diagrama feito somente da parte do usuário que quer algo emprestado. grato.
![CASO DE USO ](https://user-images.githubusercontent.com/49919267/108938598-274f9700-762f-11eb-9779-9786a039c5cf.png)

**Comment by lucasdutraf** [comment]
> Diagrama de Caso de uso 40%, peço que verifiquem e me passem feedback se está bom ou ruim e o que precisa ser mudado, diagrama feito somente da parte do usuário que quer algo emprestado. grato.
> ![CASO DE USO ](https://user-images.githubusercontent.com/49919267/108938598-274f9700-762f-11eb-9779-9786a039c5cf.png)

O que seria o usuário mutuado e usuário mutuador?

**Comment by lucasdutraf** [comment]
@matheusyanmonteiro O que seria usuário mutuado e usuário mutuador?

**Comment by matheusyanmonteiro** [comment]
@lucasdutraf mutuador é um adjetivo para quem empresta ,mutuado é quem recebe emprestado segundo o google 
coloquei assim pois estava tentando achar uma palavra que significasse empréstimo pegou e emprestou

**Comment by lucasdutraf** [comment]
> @lucasdutraf mutuador é um adjetivo para quem empresta ,mutuado é quem recebe emprestado segundo o google
> coloquei assim pois estava tentando achar uma palavra que significasse empréstimo pegou e emprestou

A nossa documentação deve estar toda de acordo em terminologia, precisamos definir os nomes para utilizarmos sempre que formos referenciar os dois tipo de usuário. O que acham dessa opção? @EsioFreitas @rogerioo @youssef-md 

Não acho ser a melhor opção por ser um linguajar mais culto.

**Comment by EsioFreitas** [comment]
Concordo. Vamos ter uma abordagem mais simplista.

Em qua., 24 de fev. de 2021 às 17:43, Lucas Dutra Ferreira do Nascimento <
notifications@github.com> escreveu:

**Comment by viniciussaturnino** [comment]
Fiz o diagrama de pacotes, se puderem me dar um feedback se tem algo faltando ou qualquer outra coisa para poder melhorar

![diagrama_pacotes](https://user-images.githubusercontent.com/49040839/109148999-c1096800-7745-11eb-93db-c39fb37e2a18.png)

**Comment by EsioFreitas** [comment]
@viniciussaturnino  , muito bom o documento! So um detalhe. Na view, ainda falta pastas. No entanto, não precisamos ir tão profundo. Tudo isso é questão de abstração e o que realmente entrega valor para a documentação. Portanto, pode tirar as pastas dentro de view.

**Comment by cantuariavc** [comment]
> @cantuariavc , muito bom o documento! So um detalhe. Na view, ainda falta pastas. No entanto, não precisamos ir tão profundo. Tudo isso é questão de abstração e o que realmente entrega valor para a documentação. Portanto, pode tirar as pastas dentro de view.

Você marcou o Vinícius errado kkkkkk

**Comment by matheusyanmonteiro** [comment]
![Capturar](https://user-images.githubusercontent.com/49919267/109157503-dafc7800-7750-11eb-8bd8-f26689de9539.JPG)
Diagrama de caso de uso em estagio final,  @lucasdutraf, @EsioFreitas , @Thais-ra, @viniciussaturnino , @rogerioo por favor dá feedback  caso esteja bom vou importar o arquivo para documentação

**Comment by lucasdutraf** [comment]
@matheusyanmonteiro na minha visão, tudo certo.

**Comment by lucasdutraf** [comment]
@matheusyanmonteiro imagino que no fluxo pensado, antes da UC06 não exista a UC05, pois listar as categorias é algo que somente a pessoa que emprestará irá fazer. Enquanto quem quer algo emprestado, apenas colocaria as labels de categorias na criação do produto.

**Comment by lucasdutraf** [comment]
> @matheusyanmonteiro imagino que no fluxo pensado, antes da UC06 não exista a UC05, pois listar as categorias é algo que somente a pessoa que emprestará irá fazer. Enquanto quem quer algo emprestado, apenas colocaria as labels de categorias na criação do produto.

@EsioFreitas @youssef-md @rogerioo

**Comment by lucasdutraf** [comment]
@matheusyanmonteiro substituir UC05 e UC06 por: Criar solicitação de emprestimo -> selecionar categorias de emprestimos

**Comment by youssef-md** [comment]
@matheusyanmonteiro você tá indo bem!

* UC 04, UC 12 :Alterar Logalização -> Localização

* UC 14 com UC 15 seria um <<extend>> já que nem sempre ele vai atender uma solicitação. Você também poderia inverter a lógica, o usuário pode aceita um empréstimo e teria um <<include>> de Pesquisar por categoria

- Falta fazer um fluxo de quando o usuário que quer algo emprestado criar um pedido a aplicação deverá notificar os usuário próximos.

Qualquer dúvida pode falar com a gente antes.

**Comment by viniciussaturnino** [comment]
Atualizei o diagrama como o @EsioFreitas pediu

![diagrama_pacotes](https://user-images.githubusercontent.com/49040839/109505868-ca633f00-7a7b-11eb-9163-d625af034bf1.png)
