### ISSUE TITLE
Documento de arquitetura pt2

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#67]
## Descrição da Issue
Finalizar documento de arquitetura.

## Tasks:
- [x] Adicionar diagrama pacotes back
- [x] Adicionar diagrama de contexto
- [x] Adicionar visão de dados

## Critérios de Aceitação:
- [x] Estar na wiki

**Comment by youssef-md** [comment]
Galera, defini os serviços que teremos [nessa issue](https://github.com/fga-eps-mds/2020.2-Lend.it/issues/72). Vou explicar o fluxo para que você consigam criar o diagrama de contexto seguindo [esse exemplo](https://pax-app.github.io/Wiki/#/docs/DS/dinamica-e-seminario-3/DiagramaContexto).

**Fluxo**:
- Front-end(Flutter) vai se comunicar com o Firebase e a API Gateway(NodeJS);
- API Gateway vai se comunicar com todos os microserviços: Usuário(NodeJS), Pedidos(Flask), Avaliação(Flask).
- Cada microserviço tem seu banco de dados independente(PostgreSQL)

Obs.: Sigam os nomes dos repositórios da [nossa org](https://github.com/Lend-it).

**Comment by Thais-ra** [comment]
![photo_2021-03-03_12-42-25](https://user-images.githubusercontent.com/35047444/109831169-f1f20d00-7c1d-11eb-8433-7eee38092d97.jpg)

Rascunho do diagrama de contexto

**Comment by youssef-md** [comment]
Muito bom @Thais-ra , só lembrando que cada microsserviço teria seu banco individual, então User teria seu próprio PostgreSQL, Resquest também e Rating também.

**Comment by Matheusafonsouza** [comment]
Primeira versão do Diagrama de Pacotes do Back-end Flask
![Diagrama em branco (3)](https://user-images.githubusercontent.com/42722634/109895487-0b22aa00-7c6e-11eb-98ae-6c7702bdc605.png)

**Comment by Matheusafonsouza** [comment]
Primeira versão do Diagrama de Pacotes do Back-end Node.js
![Diagrama em branco (4)](https://user-images.githubusercontent.com/42722634/109896527-cf88df80-7c6f-11eb-81b1-2604f6df7326.png)

**Comment by mateusmaiamaia** [comment]
Primeira versão do diagrama de contexto
![Trabalho(1)](https://user-images.githubusercontent.com/48732066/109952810-08e83c00-7cbe-11eb-851d-957e326551f5.png)

**Comment by mateusmaiamaia** [comment]
Segunda versão
![Diagrama de contexto(2)](https://user-images.githubusercontent.com/48732066/110135844-bf771a00-7dad-11eb-99d3-fa4c4bf17e79.jpg)

**Comment by thiagompc** [comment]
Visão de Dados (banco)
![modeloconceitual](https://user-images.githubusercontent.com/53379532/110033292-fb5fa000-7d17-11eb-9e84-d63912c75dcc.png)
![modelologico](https://user-images.githubusercontent.com/53379532/110033302-fe5a9080-7d17-11eb-8593-087cf07e28cd.png)

**Comment by Matheusafonsouza** [comment]
Diagrama de pacotes do back-end nodejs V2
![Uploading Diagrama em branco.png…]()

**Comment by Matheusafonsouza** [comment]
Diagrama de pacotes do back-end nodejs V2
![Diagrama em branco](https://user-images.githubusercontent.com/42722634/110132339-d156be00-7da9-11eb-9322-54a23a6d7a51.png)

**Comment by EsioFreitas** [comment]
Alterações:
* Trocar o simbulo de banco para serviço do firebase 
* conectar firebase com front
* Colocar os documentos em ordem decrescente
* colocar rascunho como v1

**Comment by mateusmaiamaia** [comment]
Terceira versão
![Diagrama de contexto(3)](https://user-images.githubusercontent.com/48732066/110218796-60db9a00-7e9a-11eb-93c6-cfb4eeb3af5d.jpg)
