### ISSUE TITLE
Prototipo de Alta fidelidade

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#70]
## Descrição da Issue
Criação do prototipo de alta fidelidade 

## Tasks:
- [x] Criação das telas
- [x] Lincar telas 

## Critérios de Aceitação:
- [x] Respeitar fluxo acordado com o time
- [x] Levar em conta os testes de usabilidade
- [x] Documentar Prototipação
