### ISSUE TITLE
Documento de Planejamento Sprint 03

### ISSUE THREAD

**Issue by rogerioo** [fga-eps-mds/2020.2-Lend.it#75]
## Descrição da Issue
Deve criar o documento de planejamento da sprint 3

## Tasks:
- [x] texto com o foco da sprint
- [x] datas de inicio e fim da sprint
- [x] linkar as issues mapeadas

## Critérios de Aceitação:
- [x] estar na wiki
