### ISSUE TITLE
Criação de design system

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#80]
## Descrição da Issue
Criação do design system da aplicação

## Tasks:
- [x] Criar design system da aplicação

## Critérios de Aceitação:
- [x] Estar documentado na wiki
- [x] Estar de acordo com a identidade visual
