### ISSUE TITLE
Configurar CD Flask

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#81]
## Descrição da Issue
Configurar CD dos ambientes Flask

## Tasks:
- Rating
- [x] Adicionar migrations
- [x] Decidir plataforma
- [x] Adicionar table no banco remoto
- [x] Criar homolog env
- [x] Criar prod env
- Request
- [x] Adicionar migrations
- [x] Decidir plataforma
- [x] Adicionar table no banco remoto
- [x] Criar homolog env
- [x] Criar prod env

## Critérios de Aceitação:
- [x] CD estar funcionando
